[package]
name = "kll-rs"
version = "0.1.0"
authors = ["Smasher816 <Smasher816@gmail.com>"]
edition = "2018"

[dependencies]
pest = { version = "2.1", features = ["pretty-print" ] }
pest_derive = "2.1"
pest_consume = "1.0"
