name: Rust

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - name: Cargo Check
        run: cargo check --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Check (kll-compiler)
        run: cargo check --manifest-path kll-compiler/Cargo.toml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - name: Cargo Build
        run: cargo build --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Build (kll-compiler)
        run: cargo build --manifest-path kll-compiler/Cargo.toml

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - name: Cargo Test
        run: cargo test --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Test (kll-compiler)
        run: cargo test --manifest-path kll-compiler/Cargo.toml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Rustfmt Check (kll-compiler)
        run: cargo fmt --manifest-path kll-compiler/Cargo.toml -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Cargo Clippy
        run: cargo clippy --all-targets -- -D warnings
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Clippy (kll-compiler)
        run: cargo clippy --manifest-path kll-compiler/Cargo.toml -- -D warnings

  doc:
    name: Doc Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-docs
      - name: Cargo Doc
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Doc (kll-compiler)
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --manifest-path kll-compiler/Cargo.toml

  udeps:
    name: cargo-udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - name: cargo-binstall
        run: |
          mkdir -p ~/.cargo/bin
          wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar xf cargo-binstall*.tgz -C ~/.cargo/bin
      - run: cargo binstall --no-confirm cargo-udeps
      - name: Cargo Udeps
        run: cargo udeps --all-targets
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Udeps (kll-compiler)
        run: cargo udeps --manifest-path kll-compiler/Cargo.toml
