name: Rust

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Cargo Check
        run: cargo check --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Check (kll-compiler)
        run: cargo check --manifest-path kll-compiler/Cargo.toml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Cargo Build
        run: cargo build --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Build (kll-compiler)
        run: cargo build --manifest-path kll-compiler/Cargo.toml

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Cargo Test
        run: cargo test --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path kll-compiler/Cargo.toml
      - name: Cargo Test
        run: cargo test --manifest-path kll-compiler/Cargo.toml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Rustfmt
        run: cargo fmt --manifest-path kll-compiler/Cargo.toml -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Cargo Clippy
        run: cargo clippy --all-targets -- -D warnings
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Clippy
        run: cargo clippy --manifest-path kll-compiler/Cargo.toml -- -D warnings

  doc:
    name: Doc Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs
      - name: Cargo Doc
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all
      # kll-compiler is std and must be kept separate from the no_std crates
      - name: Cargo Doc
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --manifest-path kll-compiler/Cargo.toml
