name: Rust

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path kll-compiler/Cargo.toml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path kll-compiler/Cargo.toml

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path kll-compiler/Cargo.toml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kll-compiler/Cargo.toml -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --manifest-path kll-compiler/Cargo.toml -- -D warnings

  doc:
    name: Doc Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all
      # Temporary action until bincode-core is converted to bincode
      - uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --manifest-path kll-compiler/Cargo.toml
